spring.application.name=demo

spring.data.mongodb.uri=mongodb://admin:12345@ac-qed0g03-shard-00-00.pf15eq9.mongodb.net:27017,ac-qed0g03-shard-00-01.pf15eq9.mongodb.net:27017,ac-qed0g03-shard-00-02.pf15eq9.mongodb.net:27017/intern_db?ssl=true&replicaSet=atlas-qmzbju-shard-0&authSource=admin&appName=Cluster0

jwt.secret=secretKey123
jwt.expiration=86400000

server.port=8080